qx:
  name: csccrt
  version: 1.0
  copyrightYear: 2021
  demoEnabled: true
  profile: D:/csccrt/uploadPath
  #profile: /home/patient/uploadPath
  addressEnabled: true

server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 30

logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

spring:
  messages:
    basename: static/i18n/messages
  profiles:
    active: druid
  servlet:
     multipart:
       max-file-size:  10MB
       max-request-size:  20MB
  devtools:
    restart:
      enabled: true
  redis:
    host: localhost
    port: 6379
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
# 解决启动报错：class path resource [processes/] cannot be resolved to URL because it does not exist
  activiti:
    check-process-definitions: false
    # 检测身份信息表是否存在
    db-identity-used: false
  
mybatis:
    typeAliasesPackage: com.qx
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    configLocation: classpath:mybatis/mybatis-config.xml

pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

xss: 
  enabled: true
  excludes: /system/notice/*
  urlPatterns: /system/*,/monitor/*,/tool/*
token:
    header: Authorization
    secret: abcdefghijklmnopqrstuvwxyz
    expireTime: 300